[bindings.swift]
generate_module_maps = true
cdylib_name = "cove_node_ffi"
omit_argument_names = false

[bindings.kotlin]
package_name = "org.bitcoinppl.cove_node"
cdylib_name = "cove_node_ffi"
omit_argument_names = false