[bindings.kotlin]
package_name = "org.bitcoinppl.cove.transaction"
cdylib_name = "cove_transaction"
omit_argument_names = false

[bindings.swift]
cdylib_name = "cove_transaction"
omit_argument_names = false

[bindings.python]
cdylib_name = "cove_transaction"
omit_argument_names = false