[package]
name = "cove"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "staticlib"]
name = "cove"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
crossbeam = "0.8.4"
parking_lot = {version = "0.12.1", features = ["deadlock_detection"]}
once_cell = "1.19.0"

# async
tokio = { version = "1.38", features = ["rt"] }

# logging
env_logger = "0.11.0"
log = "0.4.21"

# bindings
uniffi = { version = "=0.28" }

[build-dependencies]
uniffi = { version = "=0.28", features = ["build"] }

[dev-dependencies]
uniffi = { version = "=0.28", features = ["bindgen-tests"] }
