[package]
name = "cove"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "cove"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
# bdk / bitcoin
bdk_wallet = { version = "1.0.0-alpha.13", features = ["keys-bip39"] }
bip39 = { version = "2.0.0", features = ["zeroize"] }

# bitcoin nodes
bdk_esplora = { version = "0.15", features = ["async-https"] }

# TODO: update once this is merged: https://github.com/bitcoindevkit/bdk/pull/1491
bdk_electrum = { git = "https://github.com/thunderbiscuit/bdk", branch = "feature/electrum-client-ring", features = ["use-rustls-ring"], default-features = false }
electrum-client = { git = "https://github.com/thunderbiscuit/rust-electrum-client", branch = "feature/rustls-ring", features = ["use-rustls-ring"], default-features = false }
# bdk_bitcoind_rpc = { version = "0.12", features = [] }

# crypto
rand = "0.8.5"
zeroize = "1.8.1"

# concurrency
crossbeam = "0.8.4"
parking_lot = {version = "0.12.1", features = ["deadlock_detection"]}
once_cell = "1.19.0"

# error handling
eyre = "0.6"
thiserror = "1.0"

# async
tokio = { version = "1.38", features = ["rt"] }

# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"


# dirs
dirs = "5.0.1"

# database
redb = "2.1"

# ids
nid = "3.0"

# derive stuff
derive_more = "0.99.18"
strum = {version = "0.26", features = ["derive"]}

# ser/de
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

# exts
itertools = "0.13"

# bindings
uniffi = { version = "=0.28", features = ["tokio"] }

# hashing
sha2 = "0.10.8"

# bit manipulation
num-bigint = "0.4"

[build-dependencies]
uniffi = { version = "=0.28", features = ["build"] }

[dev-dependencies]
uniffi = { version = "=0.28", features = ["bindgen-tests"] }

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
strip = "debuginfo"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = "debuginfo" # Partially strip symbols from binary
