[package]
name = "cove"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "cove"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[features]
default = ["uniffi/cli"]

[dependencies]
# bdk / bitcoin
bdk_wallet = { version = "1.0.0-beta.4", features = ["keys-bip39", "file_store"] }
bip39 = { version = "2.0.0", features = ["zeroize"] }

# bitcoin nodes
bdk_esplora = {  version = "0.18", features = ["async-https"] }
bdk_electrum = { version = "0.18", features = ["use-rustls-ring"], default-features = false }
# bdk_bitcoind_rpc = { version = "0.12", features = [] }

# store bdk wallet data
bdk_file_store = { version =  "0.16.0"}
bdk_chain = { version = "0.19.0"}

# wallet import / export
pubport = { version = "0.1.0", git = "https://github.com/bitcoinppl/pubport.git", features = []}

bitcoin-units = "0.1"
bitcoin_hashes = "0.14.0"

# async / actors
tokio = { version = "1.38", features = ["rt"] }
act-zero = {version = "0.4.0", features = ["default-tokio"]}
async-trait = "0.1.81"
futures = "0.3.30"

# crypto
rand = "0.8.5"
zeroize = "1.8.1"

# concurrency
crossbeam = "0.8.4"
parking_lot = {version = "0.12.1", features = ["deadlock_detection"]}
once_cell = "1.19.0"

# error handling
eyre = "0.6"
thiserror = "1.0"


# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"


# dirs
dirs = "5.0.1"

# database
redb = "2.1"

# ids
nid = "3.0"

# derive stuff
derive_more = {version = "1.0", features = ["display", "from", "into", "as_ref", "from_str", "deref" ]}
strum = {version = "0.26", features = ["derive"]}

# helpers
tap = "1.0.1"

# time 
jiff = { version ="0.1", features = ["tz-system"] }

# ser/de
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"

# exts
itertools = "0.13"

# bindings
uniffi = { version = "=0.28.1", features = ["tokio"] }

# hashing
sha2 = "0.10.8"

# bit manipulation
num-bigint = "0.4"

# url parsing
url = "2.5"

# encryption
chacha20poly1305 = "0.10.1"
data-encoding = "2.6.0"

# fast hashmap
ahash = "0.8.11"

# fmt currency
numfmt = "1.1.1"

# http client
reqwest = { version = "0.12", features = ["json"] }

# builders
bon = "2.3"

[build-dependencies]
uniffi = { version = "=0.28.1", features = ["build"] }

[dev-dependencies]
tokio = { version = "1.38", features = ["rt", "test-util", "macros"] }
uniffi = { version = "=0.28.1", features = ["bindgen-tests"] }

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
strip = "debuginfo"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = "debuginfo" 
