max_width = 100
use_small_heuristics = "Max" # ﬂattens more constructs

# nightly
# struct_lit_single_line = true # e.g. `Foo { x: 1, y: 2 }`
# Don’t force all blocks to be multiline—this lets single‐statement blocks stay inline
# force_multiline_blocks = false # single‐statement bodies can be `{ foo(); }`
# control_brace_style = "AlwaysSameLine" # don’t move `{`/`}` to next line
